import { createSlice, createEntityAdapter } from '@reduxjs/toolkit';

const csvModules = import.meta.glob('../../vast_assets/Datasets/Activity Logs/*.csv');
const filenames = Object.keys(csvModules).map((path) => {
  return path.split('/').pop();
});

const filesAdapter = createEntityAdapter({
  selectId: (file) => file.name,
  sortComparer: (a, b) => a.name.localeCompare(b.name),
});

// The slice name must match the one used in the redux store
const filesSlice = createSlice({
  name: 'files',
  initialState: filesAdapter.getInitialState({
    ids: filenames,
    entities: filenames.reduce((acc, name) => ({ ...acc, [name]: { name } }), {}),
    selectedFileId: null,
  }),

  reducers: {
    setFiles: filesAdapter.setAll,
    selectSingleFile: (state, action) => {
      state.selectedFileId = action.payload;
    },
    toggleFileSelection: (state, action) => {
      const id = action.payload;
      const index = state.selectedFileIds.indexOf(id);
      if (index === -1) {
        state.selectedFileIds.push(id);
      } else {
        state.selectedFileIds.splice(index, 1);
      }
    },
  },
});

// Custom selector to get the specific selected object
export const getSelectedFile = (state) => {
  const allEntities = state.files.entities;
  const selectedId = state.files.selectedFileId;
  return allEntities[selectedId]; // Returns the file object or undefined
};

// Export the selectors generated by the adapter.
// Those functions are generated automatically by redux.
export const {
  selectAll: selectAllFiles,
  selectById: selectFileById,
  selectIds: selectFileIds
} = filesAdapter.getSelectors((state) => state.files);

export const { setFiles, selectSingleFile, toggleFileSelection } = filesSlice.actions;
export default filesSlice.reducer;